config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static#start'
  get 'home', to: 'static#home'
  get 'about', to: 'static#about'
  get 'why', to: 'static#why'
  get 'herbalab', to: 'static#herbalab'
  get 'herbalab/:id', to: 'static#showherb'
  get 'select', to: 'static#select'

  resources :jars
  resources :orders

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/herb.rb
class Herb < ApplicationRecord
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :herb
  belongs_to :jar

  # validates :quantity, numericality: { greater_than: 0, less_than_or_equal_to: 60 }

  def name
    herb.name
  end

  def color
    herb.color
  end
end

app/models/jar.rb
class Jar < ApplicationRecord
  belongs_to :order
  has_many :ingredients, dependent: :delete_all

  accepts_nested_attributes_for :ingredients, reject_if: proc { |a| a['quantity'].to_i < 1 }, :allow_destroy => true

  validate :must_be_full

  def fullness
    self.ingredients.map {|x| x[:quantity] }.sum
  end
  def isfull?
    return true if self.fullness == 100
    return false
  end
  def must_be_full
    unless isfull?
      errors.add(:jar, "must be full")
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :jars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include ApplicationHelper
end

app/controllers/jars_controller.rb
class JarsController < ApplicationController
  before_action :correct_order, only: [:destroy]

  def new
    baseherb = Herb.find(params[:base])
    redirect_to select_path unless baseherb.base
    addons = Herb.where(base: false, base_id: params[:base]).take(4)

    create_order unless order_exists?
    @jar = current_order.jars.build
    @jar.ingredients.build
    @herbs = addons << baseherb
  end

  def create
    @jar = current_order.jars.build(jar_params(params))
    if @jar.save
      redirect_to jars_path
    else
      redirect_to select_path
    end
  end

  def destroy
    @jar = Jar.find(params[:id])
    @jar.ingredients.delete_all
    @jar.delete
    redirect_to jars_path
  end

  def index
    redirect_to select_path unless order_exists?
    @jars = Jar.where(order_id: current_order.id)
  end


  private

    def correct_order
      @order = Jar.find(params[:id]).order
      redirect_to(current_order) unless current_order?(@order)
    end
    def jar_params(params)
      params.require(:jar).permit(:quantity, :herb_id, :jar_id, ingredients_attributes: [:herb_id, :quantity])
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def edit
    redirect_to select_path unless current_order.jars.any?
    @order = current_order
    @jars = Jar.where(order_id: @order.id)
  end

  def update
  	@order = current_order
  	if @order.update_attributes(order_params)
      flash[:success] = "Profile updated"
      redirect_to current_order
  	else
  		render 'edit'
  	end
  end

  def show
    @order = current_order
  end

  private
    def order_params
      params.require(:order).permit(:name, :surname, :email, :street, :zipcode, :city, :phone)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
	def start
	end

	def home
	end

	def about
	end

	def why
	end

	def select
		#redirect_to order_path if order_exists?
		@baseherbs = Herb.where(base: true).take(3)
	end

	def herbalab
		@herbs = Herb.all.decorate
	end

	def showherb
		@herb = Herb.find(params[:id]).decorate
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Paranapary"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  def create_order
    session[:order_id] = Order.create.id
  end

  def current_order
    @current_order = Order.find_by(id: session[:order_id])
    @current_order ||= Order.create
  end

  def current_order?(order)
    Order.find_by(id: session[:order_id]) == order
  end

  def order_exists?
    !current_order.nil?
  end
end

app/helpers/jars_helper.rb
module JarsHelper
end

app/helpers/minimal_form_helper.rb
require "minimal_form_builder"
module MinimalFormHelper
  def minimal_form_for(object, *args, &block)
    options = args.extract_options!
    simple_form_for(object, *(args << options.merge(:builder => MinimalFormBuilder)), &block)
  end

  def minimal_fields_for(*args, &block)
    options = args.extract_options!
    simple_fields_for(*(args << options.merge(:builder => MinimalFormBuilder)), &block)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/jars/_brews.html.haml
- @index = brew_counter
= content_tag :div, "", id: "herb#{@index}", class: "brew", style: "background-color: " + brew.color

app/views/jars/_jars.html.haml
.row
  .col-sm-3
    .herbscontainer
      .pot
      .herbs
        - jar.ingredients.each do |ingr|
          = content_tag :div, "", class: "brew", style: "height: #{ingr.quantity}%; background-color: #{ingr.color}"
  .col-sm-5.vcenter.ingredients
    %ul
      - jar.ingredients.each do |ingr|
        %li
          = ingr.decorate.ingr_list
    %br
    %p
      -# = link_to '< popraw', '#'
    %p
      = link_to 'x usuń', jar, method: :delete
  .col-sm-2.vcenter.counts
    liczba

-# - jar.ingredients.each do |ingr|
-#   = ingr.name
-#   = ingr.quantity

app/views/jars/_sliders.html.haml
- @index = herb_counter
= f.fields_for :ingredients do |ff|
  - if herb.base == false
    = content_tag :div, class: "divTableRow", onmouseover: "showherbdesc(\"#{herb.description}\", \"#{herb.color}\")", onmouseleave: "hide()" do
      .divTableCell.herbname
        %p.herbname= CGI.unescapeHTML(herb.name).mb_chars.upcase.to_s
      .divTableCell
        = ff.hidden_field :herb_id, :value => herb.id
        = content_tag :div,"", id: "slider#{@index}"
        = ff.hidden_field :quantity, :value => 10, :id => 'quantity' + @index.to_s
  - else
    = ff.hidden_field :herb_id, :value => herb.id
    = ff.hidden_field :quantity, :value => 40

app/views/jars/index.html.haml
- provide(:title, 'Zamów')
= render 'layouts/header'
.container
  .content.row
    .col-md-2#navmenu
      = render 'layouts/navmenu'
    .col-md-8.col-md-offset-1
      = render partial: 'jars', collection: @jars, as: :jar
      .row
        .col-sm-4
          = link_to '< chcesz coś jeszcze domieszać?', select_path
        .col-sm-4.col-sm-offset-3
          = link_to 'zamów >', edit_order_path(current_order)

app/views/jars/new.html.haml
- provide(:title, 'Namieszaj' )
= render 'layouts/header'
.container
  .content.row
    .col-md-2.col-xs-12#navmenu
      = render 'layouts/navmenu'
    .col-md-3.col-xs-4
      .herbscontainer#herbscontainer
        .herbs#herbs
          .herbe#herbe.brew
          = render partial: 'brews', collection: @herbs, as: :brew
        .pot#pot
          #potperc
      #descpopupcontainer
        #descriptionpopup
    .col-md-5.col-xs-7
      #sliders
        -# = form_tag jars_path do
        = form_for @jar do |f|
          .divTable.herbtab
            .divTableBody
              = render partial: 'sliders', collection: @herbs, as: :herb, locals: {f: f}
      = link_to content_tag(:div, "zamów".html_safe + content_tag(:div, "", id: "ordercircle"), id: "orderbutton"), ''
:javascript
  $( document ).ready( function(){

  updatesliders();
  updateheights();

    $("#orderbutton").click(function () {
        orderbutton();
    });

  });

app/views/layouts/_header.html.haml
%header.mainheader
  %h1= link_to "PARA NAPARY", home_path

app/views/layouts/_links.html.haml
= javascript_include_tag 'application', 'data-turbolinks-track' => true
= csrf_meta_tags
%link{:href => "https://fonts.googleapis.com/css?family=Lato:100,300,400&subset=latin-ext", :rel => "stylesheet"}/
%link{:href => "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/
%script{:src => "https://code.jquery.com/jquery-1.12.4.js"}
%script{:src => "https://code.jquery.com/ui/1.12.1/jquery-ui.js"}
%link{:href => "https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css", :rel => "stylesheet"}/
= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true

app/views/layouts/_navmenu.html.haml
%ol
  %li.menuitem= link_to "namieszaj", select_path
  %li.menuitem= link_to "po co to", why_path
  %li.menuitem= link_to "herba lab", herbalab_path
  %li.menuitem= link_to "o nas", about_path

app/views/layouts/application.html.haml
!!!
%html{:lang => "pl"}
  %head
    = favicon_link_tag
    %title= full_title(yield(:title))
    = render 'layouts/links'
  %body
    = yield

app/views/mix/herbalab.html.haml
- provide(:title, 'Herba lab' )
= render 'layouts/header'
.container
  .content.row
    .col-md-2#navmenu
      = render 'layouts/navmenu'
    .col-md-8.col-md-offset-1
      .herbs-img
        - @herbs.each do |herb|
          .herbblock
            = link_to image_tag("/images/herbs/" + herb.image, style: "border: 4px solid " + herb.color, onerror: "this.src='/images/empty.svg'"), { controller: "mix", action: "showherb", id: herb.id }
            %br/
            = CGI.unescapeHTML(herb.name)
      #descriptionpopup
.footer

app/views/mix/mix.html.haml
- provide(:title, 'Namieszaj' )
= render 'layouts/header'
.container
  .content.row
    .col-md-2.col-xs-12#navmenu
      = render 'layouts/navmenu'
    .col-md-3.col-xs-4
      .herbscontainer#herbscontainer
        .herbs#herbs
          .herbe#herbe.brew
          = render partial: 'brews', collection: @ingredients, as: :brew
          = content_tag :div, "", id: "herb4", class: "brew", style: "background-color: " + @baseherb.color
        .pot#pot
          #potperc
      #descpopupcontainer
        #descriptionpopup
    .col-md-5.col-xs-7
      #sliders
        = form_tag createjar_path do
          .divTable.herbtab
            .divTableBody
              = render partial: 'sliders', collection: @ingredients, as: :addon
      = link_to content_tag(:div, "zamów".html_safe + content_tag(:div, "", id: "ordercircle"), id: "orderbutton"), ''
:javascript
  $( document ).ready( function(){

  updatesliders();
  updateheights();

  $("#orderbutton").click(function () {
      orderbutton();
  });

  });

app/views/mix/order.html.haml
- provide(:title, 'Zamów')
= render 'layouts/header'
.container
  .content.row
    .col-md-2#navmenu
      = render 'layouts/navmenu'
    .col-md-8.col-md-offset-1
      = render partial: 'jars', collection: @jars, as: :jar

app/views/mix/select.html.haml
- provide(:title, 'Namieszaj')
= render 'layouts/header'
.container
  .content.row
    .col-md-2#navmenu
      = render 'layouts/navmenu'
    .col-md-8.col-md-offset-1
      .herbs-img
        .divTable{:style => "width: 120px;"}
          .divTableBody
            .divTableRow
              - @baseherbs.each do |baseherb|
                .divTableCell
                  = link_to image_tag("herbs/" + baseherb.image, style: "border: 4px solid " + baseherb.color, onmouseover: "showherbdesc(\""+baseherb.description+"\", \""+baseherb.color+"\")", onmouseleave: "hide()"), { controller: "jars", action: "new", base: baseherb.id }
                  %br/
                  = baseherb.name
      #descriptionpopup
.footer

app/views/mix/showherb.html.haml
- provide(:title, @herb.name.capitalize)
= render 'layouts/header'
.container
  .content.row
    .col-md-2#navmenu
      = render 'layouts/navmenu'
    .col-md-8.col-md-offset-1
      .herbs-img
        .herbblock
          = link_to image_tag("/images/herbs/" + @herb.image, style: "border: 4px solid " + @herb.color, onerror: "this.src='/images/empty.svg'"), '#'
          %br/
          = CGI.unescapeHTML(@herb.name)
      %p{:style => "text-align: center"} Tu napiszemy więcej o ziółkach.
.footer

app/views/orders/_jar_list.html.haml
%li
  %ul
    -jar.ingredients.each do |ingr|
      %li="#{ingr.quantity}% #{ingr.name}"

app/views/orders/_jars.html.haml
.row
  .col-sm-3
    .herbscontainer
      .pot
      .herbs
        - jar.ingredients.each do |ingr|
          = content_tag :div, "", class: "brew", style: "height: #{ingr.quantity}%; background-color: #{ingr.color}"
  .col-sm-5.vcenter.ingredients
    %ul
      - jar.ingredients.each do |ingr|
        %li
          = ingr.decorate.ingr_list
    %br
    %p
      = link_to '< popraw', '#'
    %p
      = link_to 'x usuń', jar, method: :delete
  .col-sm-2.vcenter.counts
    liczba

-# - jar.ingredients.each do |ingr|
-#   = ingr.name
-#   = ingr.quantity

app/views/orders/_small_jars.html.haml
.col-sm-2
  .smherbscontainer
    .pot
    .herbs
      - jar.ingredients.each do |ingr|
        = content_tag :div, "", class: "brew", style: "height: #{ingr.quantity}%; background-color: #{ingr.color}"

app/views/orders/edit.html.haml
- provide(:title, 'Zamów')
= render 'layouts/header'
.container
  .content.row
    .col-md-2#navmenu
      = render 'layouts/navmenu'
    .col-md-8.col-md-offset-1
      .row
        = render partial: 'small_jars', collection: @jars, as: :jar
      =minimal_form_for @order, defaults: { label: false, input_html: { class: 'form-control input-sm' }} do |f|
        .row
          .col-sm-3
            .form-group
              =f.input :name
          .col-sm-3
            .form-group
              =f.input :surname
        .row
          .col-sm-6
            .form-group
              =f.input :email
        .row
          .col-sm-6
            .form-group
              =f.input :street
        .row
          .col-sm-2
            .form-group
              =f.input :zipcode
          .col-sm-4
            .form-group
              =f.input :city
        .row
          .col-sm-6
            .form-group
              =f.input :phone
        .row
          .com-sm-6
            .form-group
              =f.submit 'Zamów!'

app/views/orders/show.html.haml
- provide(:title, 'Zamów')
= render 'layouts/header'
.container
  .content.row
    .col-md-2#navmenu
      = render 'layouts/navmenu'
    .col-md-8.col-md-offset-1
      .row
        Twoje zamówienie:
        %ol
          = render partial: 'jar_list', collection: @order.jars, as: :jar
        %p
          Wyślemy na adres:
          %b
            %br
            = "#{@order.name} #{@order.surname}"
            %br
            = "#{@order.street}"
            %br
            = "#{@order.zipcode} #{@order.city}"
            %br
            = "tel.: #{@order.phone}"
            %br
            = "#{@order.email}"
        .row
          .col-md-6
            Nie tak?
            %br
            = link_to "< Popraw!", edit_order_path(current_order)
          .col-md-5
            W porządku?
            %br
            = link_to "Zapłać przez PayU, czy coś!", '#'